### ISSUE TITLE
Feature suggestion: Documentation enhancement and/or refactoring code to use Maven

### ISSUE THREAD

**Issue by MattForshaw** [phf/jb#3]
Good evening Peter and team,

Thanks for opening up jb; it looks very promising, and I'm keen to give this a try in the next academic year.

I ran into one or two niggles building and running jb for the first time, and I wanted to propose to refactor the codebase to use Maven as a build tool. I would welcome your thoughts on this. I would be happy to commit to do a PR for this, and make necessary documentation changes.

If you would prefer to stick with the existing Makefile, I can issue a PR to help clarify the onboarding instructions.

Best wishes,
Matt

**Comment by phf** [comment]
Hi Matt,

Thanks for taking an interest! I only did the convoluted build process with make because that's what I know. I find all Java build tools strange and arcane. And huge! So I have very little incentive to learn them right now. If you think Maven is best (seemed to me that the community recently shifted to something else, although the name escapes me right now), I am happy to accept a PR. As long as it doesn't mess with the internals of the code too much that is. (I was also looking at Buck from Facebook recently, but again, it seemed too huge to get into right now. And apparently Java doesn't do "small" build tools on general principle.) So again, if you think Maven is best and if you are willing to put it together, I am happy to take it. :-)

Peter

**Comment by MattForshaw** [comment]
Hi Peter,

Thanks for the quick reply. I assume the other tool you refer to is Gradle (https://gradle.org/)?

I am a Maven user by habit, but Gradle would appear an equally good fit here.

I will spend some time this week bringing the project into Gradle and update the docs. Wherever possible, I will work to ensure the project can still be built using your Makefile so it doesn't break your way of doing things.

I will keep you posted on progress. :)

Best wishes,
Matt

**Comment by phf** [comment]
To be perfectly honest, I don't really know what I am talking about with Java build tools. If you prefer Maven, I prefer Maven. And if Maven is "smaller" than Gradle (as in fewer dependencies), I again prefer Maven. But your call, whatever you pick will be fine I am sure! Thank you for helping out!
